import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{ArrowDown,ArrowUpRight,BrainCircuit,ChartNoAxesCombined,Cloud,Code2,Download,Gamepad2,Layers3,Link,Mail,Menu,X}from'lucide-react';
import{motion,useScroll,useTransform}from'motion/react';
import'./style.css';
import'./hero.css';
import'./hero-v2.css';

const roles=[
 {period:'2025 — NOW',role:'Senior Data Scientist',company:'NielsenIQ',copy:'Modernizing forecasting systems at scale—from legacy migration and coefficient extraction to MLflow-powered experimentation and production-grade PySpark pipelines.',tags:['Forecasting','Databricks','PySpark','MLflow']},
 {period:'2022 — 2025',role:'Data Scientist · Team Lead',company:'Saama Technologies',copy:'Led a team of seven building trade promotion analytics for Unilever, including demand, price-elasticity and cannibalization models plus an LLM-powered data assistant.',tags:['Team Lead','LLMs','Azure','TPA']},
 {period:'2020 — 2022',role:'Data Scientist (L2)',company:'IVL Global',copy:'Built computer-vision, recognition and insight products—from FaceNet and YOLO APIs to business intelligence dashboards.',tags:['Computer Vision','NLP','AWS','Power BI']},
 {period:'2017 — 2020',role:'Research → Data Science',company:'IISc · Fabelizer · Abhay Tech',copy:'Cut my teeth on multispectral imagery, semantic segmentation, speech models, document intelligence and production Flask APIs.',tags:['Deep Learning','OCR','RASA','Research']}
];
const capabilities=[
 {icon:ChartNoAxesCombined,title:'Forecasting systems',text:'Reliable engines, post-processing guardrails and large-scale validation built for real business decisions.'},
 {icon:BrainCircuit,title:'Applied machine learning',text:'From elasticity and segmentation to computer vision, NLP and conversational AI.'},
 {icon:Cloud,title:'Cloud & MLOps',text:'Azure, Databricks, ADLS, ADF and MLflow workflows engineered for production.'},
 {icon:Layers3,title:'Technical leadership',text:'Architecture, stakeholder alignment, team development and hands-on delivery—end to end.'}
];
const work=[
 {n:'01',eyebrow:'FORECASTING · NIELSENIQ',title:'Forecast at scale',text:'Price forecasting, traffic-light classification, model guardrails, test benches and robust observability—designed to make every run more trustworthy.',className:'work-a'},
 {n:'02',eyebrow:'GENERATIVE AI · UNILEVER',title:'Ask the data',text:'A conversational data assistant combining LangChain, ChatGPT and Azure Cognitive Search for fast, useful answers across enterprise data.',className:'work-b'},
 {n:'03',eyebrow:'COMPUTER VISION · PIT500',title:'Vision in motion',text:'Recognition APIs for people, places, bike accessories and brands, shipped alongside an insight-rich analytics dashboard.',className:'work-c'}
];

function App(){
 const[open,setOpen]=useState(false);const[scrolled,setScrolled]=useState(false);
 const{scrollY}=useScroll();const heroY=useTransform(scrollY,[0,850],[0,-210]);const heroScale=useTransform(scrollY,[0,850],[1,1.08]);const heroOpacity=useTransform(scrollY,[0,720],[1,.12]);const nameY=useTransform(scrollY,[0,800],[0,-80]);
 useEffect(()=>{const fn=()=>setScrolled(scrollY>20);addEventListener('scroll',fn);const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('in')), {threshold:.12});document.querySelectorAll('.reveal').forEach(el=>obs.observe(el));return()=>{removeEventListener('scroll',fn);obs.disconnect()}},[]);
 const go=()=>setOpen(false);
 return <>
  <nav className={scrolled?'scrolled':''}><a className="mark" href="#top">YA<span>.</span></a><div className={open?'navlinks open':'navlinks'}><a onClick={go} href="#about">About</a><a onClick={go} href="#work">Work</a><a onClick={go} href="#experience">Experience</a><a onClick={go} href="#contact">Contact</a><a onClick={go} className="nav-resume" href="mailto:awateyogeshs@gmail.com?subject=Résumé request">Request résumé <ArrowUpRight size={15}/></a></div><button className="menu" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></nav>
  <main id="top">
   <section className="hero"><div className="aurora a1"/><div className="aurora a2"/><div className="aurora a3"/><div className="noise"/><div className="hero-content reveal"><div className="availability"><i/> Available for meaningful problems</div><p className="kicker">SENIOR DATA SCIENTIST</p><h1>Data into<br/><span>direction.</span></h1><div className="hero-actions"><a className="button light" href="#work">Explore work <ArrowDown size={17}/></a></div></div><motion.div className="hero-name" style={{y:nameY}}>YOGESH<br/>AWATE</motion.div><motion.div className="hero-visual" style={{y:heroY,scale:heroScale,opacity:heroOpacity}} aria-hidden="true"><img src="./assets/yogesh-suit-portrait.webp" alt=""/><div className="character-shadow"/></motion.div><aside className="hero-side reveal"><p>I build forecasting systems, intelligent products and high-performing data teams.</p><a href="mailto:awateyogeshs@gmail.com"><Mail size={18}/> awateyogeshs@gmail.com</a><span>PUNE, INDIA · OPEN TO CONVERSATIONS</span></aside><div className="scroll-tag">SCROLL TO EXPLORE <span/></div></section>
   <section id="about" className="section about"><div className="section-tag reveal">01 / ABOUT</div><div className="about-lead reveal"><p>THE SHORT VERSION</p><h2>Curious by nature.<br/>Rigorous by practice.</h2></div><div className="about-grid"><p className="big-copy reveal">For 7+ years, I’ve worked where <em>machine learning</em>, engineering and business meet.</p><div className="body-copy reveal"><p>My work spans large-scale forecasting, trade promotion analytics, computer vision, NLP and generative AI. I care about elegant models—but even more about the systems and people that make them useful.</p><p>When I’m away from a notebook or whiteboard, you’ll usually find me unwinding with a controller in hand. Gaming keeps my love for systems, strategy and beautifully designed experiences alive.</p><div className="stat-row"><div><strong>7+</strong><span>Years in data</span></div><div><strong>7</strong><span>People led</span></div><div><strong>5</strong><span>Industries touched</span></div></div></div></div>
   </section>
   <section className="section capabilities"><div className="section-head reveal"><div><span className="section-tag">02 / CAPABILITIES</span><h2>What I bring<br/>to the table.</h2></div><p>Deep technical range, grounded in outcomes.</p></div><div className="cap-grid">{capabilities.map((c,i)=><article className="cap-card reveal" key={c.title}><span>0{i+1}</span><c.icon/><h3>{c.title}</h3><p>{c.text}</p></article>)}</div></section>
   <section id="work" className="section work"><div className="section-head reveal"><div><span className="section-tag">03 / SELECTED WORK</span><h2>Built for impact.</h2></div><p>A few problems I’ve enjoyed solving.</p></div><div className="work-list">{work.map(w=><article className={`work-card ${w.className} reveal`} key={w.n}><div className="work-art"><div className="mesh"/><span>{w.n}</span></div><div className="work-copy"><small>{w.eyebrow}</small><h3>{w.title}</h3><p>{w.text}</p><div className="case-link">CASE SNAPSHOT <ArrowUpRight size={15}/></div></div></article>)}</div></section>
   <section id="experience" className="section experience"><div className="section-head reveal"><div><span className="section-tag">04 / EXPERIENCE</span><h2>The journey so far.</h2></div></div><div className="timeline">{roles.map((r,i)=><article className="role reveal" key={r.period}><div className="role-num">0{i+1}</div><div className="period">{r.period}</div><div className="role-main"><h3>{r.role}</h3><h4>{r.company}</h4><p>{r.copy}</p><div className="tags">{r.tags.map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div><a className="download reveal" href="mailto:awateyogeshs@gmail.com?subject=Résumé request"><Download size={18}/> Request full résumé</a></section>
   <section className="section play"><div className="play-card reveal"><div className="play-copy"><span className="section-tag">OFF THE CLOCK</span><h2>Serious about data.<br/><em>Playful about life.</em></h2><p>Great games reward curiosity, iteration and systems thinking. Coincidentally, so does great data science.</p></div><Gamepad2 className="pad" strokeWidth={1}/><div className="orbit o1"/><div className="orbit o2"/></div></section>
   <section id="contact" className="contact"><p className="section-tag reveal">05 / LET’S CONNECT</p><h2 className="reveal">Have a hard problem?<br/><span>Let’s make it simple.</span></h2><a className="email reveal" href="mailto:awateyogeshs@gmail.com">awateyogeshs@gmail.com <ArrowUpRight/></a><div className="socials reveal"><a href="https://www.linkedin.com/in/yogesh-s-awate/" target="_blank"><Link size={18}/> LinkedIn</a><a href="https://medium.com/@yogeshinawate" target="_blank"><Code2 size={18}/> Medium</a><a href="mailto:awateyogeshs@gmail.com"><Mail size={18}/> Email</a></div></section>
  </main><footer><a className="mark" href="#top">YA<span>.</span></a><p>Designed around data, built with intent.</p><span>© 2026 YOGESH AWATE</span></footer>
 </>
}
createRoot(document.getElementById('root')).render(<App/>);
